tools/swift-format/Sources/Rules/NoEmptyTrailingClosureParentheses.swift
tools/swift-format/Tests/SwiftFormatTests/NoEmptyTrailingClosureParenthesesTests.swift

The existing implementation of the `NoEmptyTrailingClosureParentheses` rule would misidentify the following code as failing the rule:
```
func myfunc(cls: MyClass) {
cls.myClosure { $0 }
}
```
It should pass, since no parentheses are used before the trailing closure. Additionally, the rule would print `cls` to the user as the location of the error. With these changes, it would now print `myClosure`.

Fix Triggering Conditions for NoEmptyTrailingClosureParentheses Rule

---

tools/swift-format/Sources/Rules/ColonWhitespace.swift
tools/swift-format/Tests/SwiftFormatTests/ColonWhitespaceTests.swift

The `ColonWhitespace` rule was incorrectly flagging an error for empty dictionary declarations:
```
let a = [:]
```
It was requiring a space after this colon, when none are needed in this situation.

Properly handle colons for empty dictionary declarations

---

tools/swift-format/Sources/Rules/NoLeadingUnderscores.swift
tools/swift-format/Tests/SwiftFormatTests/NoLeadingUnderscoresTests.swift

This fixes a couple issues with the original implementation; it would flag identifiers that were *only* the underscore as invalid:
* Intentionally ignoring a binding in a pattern, like `let _ as Foo`
* The use of the underscore to suppress an argument label, like `func foo(_ bar: Int)`. Furthermore, for function arguments, we now only check the parameter name, not the label.
This change also cleans up some of the visitation logic (instead of iterating over a function's arguments to diagnose them, we override the corresponding `visit` methods) and breaks up the test cases into smaller independent units.

Clean up/fix NoLeadingUnderscores.

---

Sources/PrettyPrint/PrettyPrint.swift
Sources/PrettyPrint/Token.swift
Sources/PrettyPrint/TokenStreamCreator.swift

The ability to specify an offset on individual breaks will give us greater flexibility, fine-grained control on indents, and the ability to use different indentation within a single group.
Because the `visit` methods visit the parent nodes first, the tokens in the `after` array are added for the parents before the children, which puts them out of order. This ordering is fine for `before` tokens. The `after` tokens are grouped together for each call to a `visit` method, and then the groups are visited in reverse to ensure that the child's tokens are added to the stream before the parent.

Add offsets to breaks, and fix order for "after" tokens.

---

Sources/swiftformat/Run.swift
Sources/swiftformat/main.swift

Leave the pretty-printer off by default while it is still under development. It can be activated by command line flags `--pretty-print` or `-p`.

Add flag to optionally use pretty-printer

---

Sources/PrettyPrint/PrettyPrint.swift
Sources/PrettyPrint/Token.swift
Sources/PrettyPrint/TokenStreamCreator.swift
Tests/PrettyPrinterTests/IfStmtTests.swift

This fixes a bug where `newline` tokens were being assigned negative length values. This was throwing off the length calculations of `break` and `open` tokens, and causing line breaks at incorrect locations. The size of `newline` tokens have constant length, and don't require a calculation the way that normal `break` and `open` tokens do.
The stack used to keep track of `break` indent values is removed, and we instead use flags that track the offset and total indent size of the `break`, which is used by subsequent `open` and `syntax` tokens during printing. The intended behavior is that a `break` token's offset should only affect the token or group immediately following it. If a group immediately follows a `break`, the entire group will be indented according to the `break` token's offset.

Fix `newline` token length calculation

---

Sources/PrettyPrint/PrettyPrint.swift
Sources/PrettyPrint/TokenStreamCreator.swift
Tests/PrettyPrinterTests/ClassDeclTests.swift

Support for class declarations is added to the pretty printer.
This PR also fixes a minor bug where `lastBreakOffset` needs to be adjusted when it's group closes, since these offsets are relative to the indent of its group. Otherwise you could end up with negative values for the indent after the group closes.
This PR also updates the behavior of break tokens. If a break token creates a line break, and second break token occurs without first encountering a syntax token, the second break does not create a line break or emit whitespace. This is needed because the implementation of class declaration visit methods requires a case where two breaks occur in this fashion (in between the "inheritance clause" and the "where clause", which is needed to ensure the opening brace is forced to a new …

Support class declarations

---

Sources/PrettyPrint/PrettyPrint.swift
Sources/PrettyPrint/Token.swift
Sources/PrettyPrint/TokenStreamCreator.swift
Tests/PrettyPrinterTests/ArrayDeclTests.swift
Tests/PrettyPrinterTests/ForInStmtTests.swift
Tests/PrettyPrinterTests/VariableDeclTests.swift

This PR implements wrapping for Array declarations. In order to do this, the behavior of variable declarations needed to be adjusted in order to get the indentation correct. To this end, a new "space" token type is introduced. Like breaks, this token adds whitespace when encountered, except that it does not allow new lines to occur.
The line wrapping for variable declarations and for-in statements have changed. Please refer to the unit tests.

Add supports for Array declarations

---

Sources/PrettyPrint/PrettyPrint.swift
Sources/PrettyPrint/TokenStreamCreator.swift
Tests/PrettyPrinterTests/SwitchStmtTests.swift

This fixes a bug where you can have runaway indentation when you have multiple nested groups with non-zero indentation. For example:
```
if a == c {
switch square + diceRoll {
case finalSquare:
let c = 456
case nextSquare:
let a = 123
let b = "abc"
default:
square += diceRoll
square += board[square]
}
}
```
This is because the offset of the trailing break tokens aren't being adjusted properly when their enclosing group closes. They should be adjusted by the *relative* indentation of its enclosing group, and not the absolute indentation.

Fix issue where multiple nested groups could have runaway indentation

---

Sources/PrettyPrint/TokenStreamCreator.swift
Tests/PrettyPrinterTests/CompilerControlTests.swift

This PR adds `#if/#elseif/#endif` blocks. `if #available` doesn't appear to be showing up in the correct AST node, and `#error/#warning` cause the formatter to crash, so they will be addressed in later PRs.

Add support for #if compiler control statements

---

Sources/SwiftFormatCore/SyntaxLintRule.swift

The linter was reporting incorrect line numbers for some lint violations. The reason is that the reported location started at an AST node's leading trivia, rather than the node itself. This change reports the line number ignoring the leading trivia.

The line numbers of nodes should be reported ignoring leading trivia

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/CommentTests.swift

This fixes the behavior of comments (particularly trailing line comments) in cases where indentation is present, and within function declarations where the function may not contain anything except a comment.
This takes advantage of the fact that if a comment is a trailing line comment, it will appear as the first piece of the leading trivia (any whitespace in front of the comment will be trailing trivia on the preceding token). Otherwise, the first piece will be a newline.
This also handles the case where comments appear inside of container classes (i.e. Arrays, Dictionaries, etc.), where we force a newline after the comment.

Fixes to comment behavior

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/ArrayDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/DictionaryDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/TupleDeclTests.swift

Originally, I was using the delimiting comma in containers (Arrrays, Dictionaries, and Tuples) to insert breaks. This would result in wrong indentation for the closing bracket if a trailing comma was used. 
```
A = [
1,
2,
3,
]
```
This PR inserts the breaks between the elements without referencing the comma.

Fix wrapping for containers with a trailing comma

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/AsExprTests.swift

Previously, we were unconditionally breaking after the `as` keyword, which would produce code like this if there was a question mark or exclamation point: `if let foo = bar as ?Baz`

Fix breaking around `as` when followed by `?` or `!`.

---

Sources/SwiftFormatRules/CommentWhitespace.swift
Sources/swift-format/PopulatePipeline.swift
Tests/SwiftFormatRulesTests/CommentWhitespaceTest.swift

Since the pretty printer handles the insertion of spaces before an end-of-line comment, this phase-1 rule can be reduced to lint-only.
This change also removes the requirement that a single space follow the `//` sigil, which was well-intentioned but screws up the banner lines on Swift's own file headers. Trying to intelligently determine what's a banner and what's prose doesn't seem worthwhile.

Make CommentWhitespace a lint-only rule.

---

Sources/generate-pipeline/main.swift
Sources/swift-format/PopulatePipeline.swift

This eliminates two sources of nondeterminism when generating the pipeline
(which was causing some ugly diffs): FileManager's order of iteration is
dependent on the underlying file system, and dictionary key hashing is not
guaranteed to be consistent across different runs.

Sort files/rules when generating the pipeline.

---

Sources/SwiftFormatRules/CaseIndentLevelEqualsSwitch.swift
Sources/swift-format/PopulatePipeline.swift
Tests/SwiftFormatRulesTests/CaseIndentLevelEqualsSwitchTests.swift

The pretty printer will handle reïndenting cases; this also fixes a bug
where comments between cases were being discarded.

Make case indentation rule lint-only.

---

Documentation/PrettyPrinter.md

The first half of the pretty-printer algorithm documentation: the token types are described here. The second half will describe the `print` and `scan` phases of the algorithm.
Note: @allevato The Comment and Reset subsections are new.

Documentation: Introduce printer algorithm and describe token types

---

Sources/SwiftFormatPrettyPrint/PrettyPrint.swift
Sources/SwiftFormatPrettyPrint/Token.swift
Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Sources/SwiftFormatPrettyPrint/Verbatim.swift
Tests/SwiftFormatPrettyPrintTests/AttributeTests.swift
Tests/SwiftFormatPrettyPrintTests/UnknownStmtTests.swift

Some pieces of syntax are not yet known to SwiftSyntax, so they get represented as `UnknownStmtSyntax` nodes. We print these verbatim, since we don't have the ability to format them as we would a typical syntax node. To this end, a new `verbatim` token has been created, which has an associated `Verbatim` object.
The purpose of the `Verbatim` class is to handle printing while obeying the current indentation level. It performs the following steps:
- Split the source text into an array of strings by line.
- Find the number of leading whitespaces for the first line.
- Subtract this from the leading whitespace of all lines if possible.
- Print the text line by line, inserting the new amount of leading whitespace plus the given indentation level.

Add support for UnknownStmtSyntax

---

Sources/generate-pipeline/main.swift
Sources/swift-format/PopulatePipeline.swift

The `UseEarlyExits` rule might make the following transformation:
```swift
let v = ReturnAnOptional()
if let v = v {
```
to
```swift
let v = ReturnAnOptional()
guard let v = v else {
```
This will cause a build failure since the scoping is different for `if let` and `guard let`.

Deactivate UseEarlyExits rule; not safe to use

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/ClassDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/EnumDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/ExtensionDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/ProtocolDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/StructDeclTests.swift

This change also does a little rearranging of the order of the TokenStreamCreator visit methods to try to keep related things together; I'll be doing more of this in future PRs.

Fix formatting of empty type declarations.

---

Sources/SwiftFormatPrettyPrint/PrettyPrint.swift
Tests/SwiftFormatPrettyPrintTests/StringTests.swift

If a Verbatim token have multiple lines, they have a length equal to the maximum line width. If they are single-line, the length is equal to the number of characters.

Correct the Verbatim Token Length Calculation

---

Sources/SwiftFormatCore/Trivia+Convenience.swift
Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/CommentTests.swift

This PR fixes a situation where code with a trailing line comment might wrap in the following way:
```swift
guard let a = SomeOptional() else { return value  // comment
}
```
wraps to
```swift
guard let a = SomeOptional() else { return value  // comment }
```
which will cause a build failure.

Fix an edge case for trailing comments

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/DeinitializerDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/FunctionDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/InitializerDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/SubscriptDeclTests.swift

Getting this working was a slog. Some of the things I did here (like checking whether the body is empty of syntax nodes *OR* comments) need to be ported back to the type decl visitors as well, which I'll do in the next PR.

Refactor function-like decls, remove spaces in empty bodies.

---

Sources/SwiftFormatRules/AvoidInitializersForLiterals.swift
Sources/swift-format/PopulatePipeline.swift
Tests/SwiftFormatRulesTests/AvoidInitializersForLiteralsTests.swift

This PR addresses two issues with the `AvoidInitializersForLiterals` rule:
1. Trailing whitespace was not preserved. For example:
```swift
if someValue == Int(2) || anotherValue != Int(3) {
```
would transform to
```swift
if someValue == 2 as Int|| anotherValue != 3 as Int{
```
which would result in a build failure.
2. If an initializer used a labeled argument, it would get transformed anyways, possibly resulting in erroneous behavior: `Int(bitPattern: 123456)` transforms to `123456 as Int`.
We now preserve the trailing trivia of the original syntax node after transforming, and we do not transform initializers that use labeled arguments, or have more than one argument.

Correct the behavior of AvoidInitializersForLiterals

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/ForInStmtTests.swift
Tests/SwiftFormatPrettyPrintTests/FunctionCallTests.swift
Tests/SwiftFormatPrettyPrintTests/FunctionDeclTests.swift

I departed from the pattern slightly for `do/catch` blocks and used a `maxlinelength` break there to force the body to wrap even if it fits on a single line, because I didn't like the way this came out:
```swift
do { foo() } catch error as FooError { bar() } catch error as BarError { baz() }
```
Things also got a little weird if a wrap was needed in the middle of that. Since we're likely to force the `catch` lines onto their own line instead of keeping them right after the `}`, I punted on it for now and just preserved existing test behavior.

Refactor indentation of control flow statements.

---

Sources/SwiftFormatConfiguration/Configuration.swift
Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/AccessorTests.swift
Tests/SwiftFormatPrettyPrintTests/AsExprTests.swift
Tests/SwiftFormatPrettyPrintTests/DeinitializerDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/ForInStmtTests.swift
Tests/SwiftFormatPrettyPrintTests/FunctionCallTests.swift
Tests/SwiftFormatPrettyPrintTests/FunctionDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/IfStmtTests.swift
Tests/SwiftFormatPrettyPrintTests/InitializerDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/SubscriptDeclTests.swift
Tests/SwiftFormatPrettyPrintTests/TernaryExprTests.swift
Tests/SwiftFormatPrettyPrintTests/TryCatchTests.swift

This may not be perfect to handle all cases, but it's a step in that direction.
The only weird cases are situations like this:
```swift
let c = d
as Int
```
which break more aggressively if we throw in discretionary line breaks:
```swift
let c =
d
as Int
```
We're still "preserving the line break the user put there", but we're also inserting a new one "unnecessarily" because the group surrounding the RHS of the equal sign (`d as Int`) is now so large due to the max-line-length break at the discretionary newline that it causes the break before it to fire.
I'm not sure what to do about that, except to remove the group around the RHS. Maybe that _is_ the right thing to do in this case?

[Tweaks] First cut of discretionary line break handling.

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/ClosureExprTests.swift
Tests/SwiftFormatPrettyPrintTests/FunctionCallTests.swift
Tests/SwiftFormatPrettyPrintTests/TupleDeclTests.swift

This change also ended up hitting tuples in an interesting way, so I took the opportunity to make them inconsistent breaking. I'll do dictionaries and arrays in a follow-up PR. I also removed an invalid test case (tuples can't have trailing commas).
That being said, this could use a sanity check.

Make line break before closing paren discretionary.

---

Sources/SwiftFormatConfiguration/Configuration.swift
Sources/SwiftFormatConfiguration/Indent.swift
Sources/SwiftFormatPrettyPrint/Indent+Length.swift
Sources/swift-format/Run.swift
Sources/swift-format/main.swift

- Add a `--configuration` option that lets the user pass the path to a
JSON file that will be loaded instead of the default configuration.
- Add a new mode (`--mode=dump-configuration`) that dumps the default
configuration as JSON to standard output, so users can start with
that and edit it.
- Make `Indent` an enum instead of a struct.
- Manually write the decode/encode methods (sigh) so that values can
be omitted from the JSON (by default, decoding throws an error if
a value is missing, even if the default value is present in the
property initializer).

Improve the formatter configuration.

---

Sources/swift-format/DebugOptions.swift
Sources/swift-format/Run.swift
Sources/swift-format/main.swift

It can be disabled (intended for development/debugging purposes only)
using the `--debug-disable-pretty-print` option.
This change also renames `--print-token-stream` to
`--debug-dump-token-stream`; going forward, we should namespace all
options intended for debugging with the prefix `--debug-*`.
These debugging options intentionally have no "usage" strings, which
hides them from the `--help` screen. In a future PR, we can update the
README to mention them (it needs a bigger overhaul that I don't want to
include in this PR).

Enable the pretty-printer pass by default.

---

Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/UnknownStmtTests.swift

We weren't checking for trailing line comments after verbatim tokens, so they were not getting printed.

Fix trailing line comments after verbatim tokens

---

Sources/swift-format/CommandLineOptions.swift
Sources/swift-format/Run.swift
Sources/swift-format/main.swift

When running in `format` mode, a user can specify `--in-place` or `-i` to replace the input file with a formatted version.

Add an option to format a file in-place.

---

Sources/SwiftFormatPrettyPrint/PrettyPrint.swift
Sources/SwiftFormatPrettyPrint/Token.swift
Sources/SwiftFormatPrettyPrint/TokenStreamCreator.swift
Tests/SwiftFormatPrettyPrintTests/FunctionDeclTests.swift

Previously, discretionary newlines could appear anywhere that a break was
allowed. Some breaks, however, exist only as "last resorts" to allow a
line break to occur when there is no other way to break the tokens before
it. To handle this, we add a flag to breaks that allows them to discard
the user's newline unless that last resort behavior occurs.

Allow breaks to ignore discretionary newlines.

---

Package.swift
Sources/CommonMark/CMarkInterop.swift
Sources/CommonMark/HeadingNode.swift
Sources/CommonMark/MarkdownRewriter.swift
Sources/CommonMark/MarkdownVisitor.swift
Sources/CommonMark/PrimitiveNode.swift
Sources/CommonMark/ThematicBreakNode.swift
Tests/CommonMarkTests/MarkdownDocumentTest.swift
Tests/CommonMarkTests/MarkdownRenderingTest.swift

The names of some of the node types changed, so I've updated the Swift versions to match. The new names are closer to the terms of art used in the Commonmark specification.

Update cmark submodule to latest version.

---

Package.swift
Sources/SwiftFormat/SwiftLinter.swift
Sources/SwiftFormatWhitespaceLinter/WhitespaceLinter.swift
Tests/SwiftFormatWhitespaceLinterTests/WhitespaceLintTests.swift
Tests/SwiftFormatWhitespaceLinterTests/WhitespaceTestCase.swift

Currently, the way we handle linting for whitespace is to use Stage 1 rules, implemented in `Sources/SwiftFormatRules`. The pretty-printer now handles all formatting of whitespace in a Swift file. It does not have linting capability, so we have to maintain separate Stage 1 rules for the purposes of linting whitespace.
The changes introduced in this PR use the output of the pretty-printer and compares it to the user's input text to check for whitespace lint errors. This means that any changes we make to the pretty-printer's handling of whitespace will automatically result in the appropriate linter errors without the need to maintain separate Stage 1.
Note: In format mode, the pretty-printer receives the head AST node after the Stage 1 rules have had a chance to transform it. In this …

Use the pretty-printer output for whitespace linting

---

Sources/SwiftFormat/SwiftFormatError.swift
Sources/SwiftFormat/SwiftFormatter.swift
Sources/SwiftFormat/SwiftLinter.swift

Explicitly handle the case where an input file doesn't exist, and emit an appropriate error.

More gracefully check that an input file exists
